# Generated by Django 4.1.3 on 2023-01-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
