# Generated by Django 4.1.3 on 2023-01-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="isDelevered",
            new_name="isDelivered",
        ),
    ]
